spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: "/"

---
security:
  remember-me:
    cookie:
      domain: localhost
      max-age: 168
    hash-type: MD5
  oauth:
    tokens:
      issuer: authentication
      audience: '*'
      expiration:
        user:
          access: 1800
          id: 180
        service:
          access: 120
  keys:
    location: ${user.home}/.keys/
    private: private.key
    public: public.key