spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: "/"

---
security:
  oauth:
    tokens:
      issuer: id-server
      audience: '*'
      expiration:
        user:
          access: 240
          id: 60
        service:
          access: 60
  keys:
    location: ${user.home}/.keys/
    private: private.key
    public: public.key